# general settings
name: 001_VideoCompressor_FSTRN_Vimeo90k_250k_crf27
model_type: MultiFrameCompressModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KMultipleGTTrainDataset
    dataroot_gt: /data2/yangxi/datasets/Vimeo90k/vimeo_septuplet_BIx2_h264_all_com_crf27_img/sequences
    dataroot_lq: /data2/yangxi/datasets/Vimeo90k/vimeo_septuplet_BIx2_h264_all_enh/sequences
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    num_frame: 7
    gt_size: 192
    random_reverse: true
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: Vimeo90K
    type: Vimeo90KMultipleGTValidDataset
    dataroot_gt: /data2/yangxi/datasets/Vimeo90k/vimeo_septuplet_BIx2_h264_all_com_crf27_img/sequences
    dataroot_lq: /data2/yangxi/datasets/Vimeo90k/vimeo_septuplet_BIx2_h264_all_enh/sequences
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_valid_GT.txt
    io_backend:
      type: disk

    num_frame: 7

# network structures
network_g:
  type: FSTRN
  ks: 3
  nf: 64

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
